language: si

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexEntityExtractor
    use_lookup_tables: True
    use_regexes: True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    constrain_similarities: true
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    constrain_similarities: true
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 3
    epochs: 100
  - name: TEDPolicy
    max_history: 3
    epochs: 100
    constrain_similarities: true
